name: PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0b14f54
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
